// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ2O9AwhmRzyIU-PDIzHJ7vQM0NFq0vDs',
    appId: '1:809119698945:web:2ab49c94fe2c4e0393f000',
    messagingSenderId: '809119698945',
    projectId: 'a-eye-eacd2',
    authDomain: 'a-eye-eacd2.firebaseapp.com',
    storageBucket: 'a-eye-eacd2.appspot.com',
    measurementId: 'G-QEWC1G7MH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVVeNFbGPlYv5IpCUhAWsCN5CkZ-tOtv0',
    appId: '1:809119698945:android:5e341edb97918ffc93f000',
    messagingSenderId: '809119698945',
    projectId: 'a-eye-eacd2',
    storageBucket: 'a-eye-eacd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrHYAJZ4mHOEJmkbjXPC65b4awZ61YxQ',
    appId: '1:809119698945:ios:b0a6f5d6c930f43f93f000',
    messagingSenderId: '809119698945',
    projectId: 'a-eye-eacd2',
    storageBucket: 'a-eye-eacd2.appspot.com',
    androidClientId: '809119698945-3fgiq1286of1n07r4u59vliv9598dcvm.apps.googleusercontent.com',
    iosClientId: '809119698945-6pofm32fuskv97impq5m5l20kb5eju5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.aEye',
  );
}
