Map labelsMap = {
  'Person': true,
  'Bicycle': true,
  'Car': true,
  'Motorcycle': true,
  'Airplane': false,
  'Bus': true,
  'Train': false,
  'Truck': true,
  'Boat': false,
  'Traffic light': false,
  'Fire hydrant': false,
  'Stop sign': false,
  'Parking meter': false,
  'Bench': false,
  'Bird': true,
  'Cat': true,
  'Dog': true,
  'Horse': false,
  'Sheep': false,
  'Cow': false,
  'Elephant': false,
  'Bear': false,
  'Zebra': false,
  'Giraffe': false,
  'Backpack': false,
  'Umbrella': false,
  'Handbag': false,
  'Tie': false,
  'Suitcase': false,
  'Frisbee': false,
  'Skis': false,
  'Snowboard': false,
  'Sports ball': false,
  'Kite': false,
  'Baseball bat': false,
  'Baseball glove': false,
  'Skateboard': false,
  'Surfboard': false,
  'Tennis racket': false,
  'Bottle': false,
  'Wine glass': false,
  'Cup': false,
  'Fork': false,
  'Knife': false,
  'Spoon': false,
  'Bowl': false,
  'Banana': false,
  'Apple': false,
  'Sandwich': false,
  'Orange': false,
  'Broccoli': false,
  'Carrot': false,
  'Hot dog': false,
  'Pizza': false,
  'Donut': false,
  'Cake': false,
  'Chair': true,
  'Couch': false,
  'Potted plant': true,
  'Bed': false,
  'Dining table': false,
  'Toilet': false,
  'TV': true,
  'Laptop': false,
  'Mouse': true,
  'Remote': true,
  'Keyboard': true,
  'Cell phone': true,
  'Microwave': false,
  'Oven': false,
  'Toaster': false,
  'Sink': false,
  'Refrigerator': false,
  'Book': false,
  'Clock': false,
  'Vase': false,
  'Scissors': false,
  'Teddy bear': false,
  'Hair drier': false,
  'Toothbrush': false
};

Map getMap() {
  return labelsMap;
}
